# -*- coding: utf-8 -*-
"""MunicipiosTemplates.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dJDkOJRnoJh8QxcU04PrWAyE-7nFRLSR
"""

municipios = """Belo Horizonte	;	https://transparencia.pbh.gov.br/
Uberlândia	;	https://www.uberlandia.mg.gov.br/portal-da-transparencia/
Contagem	;	http://www.contagem.mg.gov.br/transparencia/
Juiz de Fora	;	https://www.pjf.mg.gov.br/transparencia/
Betim	;	http://www.betim.mg.gov.br/transparencia/
Montes Claros	;	https://transparencia.montesclaros.mg.gov.br
Ribeirão das Neves	;	http://ribeirao.supernova.com.br:8090/contaspublicas/
Uberaba	;	http://www.uberaba.mg.gov.br/portal/conteudo,37644
Governador Valadares	;	https://transparencia.valadares.mg.gov.br/
Ipatinga	;	https://transparencia.ipatinga.mg.gov.br/
Sete Lagoas	;	https://transparencia.setelagoas.mg.gov.br/
Divinópolis	;	http://177.69.246.151:8090/portalcidadao/#efb33c382dcf9e4ae2294337ce2a566034ee25478c90493e56f55878a4d19d547154abb93a539ca141901243121b0442f68667740d76583a9b6fc842805a701255f50abffb83548323feb3d4a215dcba05fc4b5b868699999c1d78af95bbbed2ae7ab27d940f9f7a8b2debb75557ba1cd7f6303c3be5a0edaecf72a00208c722773c5ec1c75725b2
Santa Luzia	;	https://www.santaluzia.mg.gov.br/v2/index.php/portal-da-transparencia/
Ibirité	;	https://webibirite.supernova.com.br:8443/contaspublicas/
Poços de Caldas	;	http://grpweb.pocosdecaldas.mg.gov.br:8081/portalcidadao/#efb33c382dcf9e4ae2294337ce2a566034ee25478c90493e56f55878a4d19d547154abb93a539ca141901243121b0442f68667740d76583a9b6fc842805a701255f50abffb83548323feb3d4a215dcba05fc4b5b868699999c1d78af95bbbed2ae7ab27d940f9f7a8b2debb75557ba1cd7f6303c3be5a0edaecf72a00208c722773c5ec1c75725b2
Patos de Minas	;	http://www.transparencia.patosdeminas.mg.gov.br/
Pouso Alegre	;	https://pousoalegre.atende.net/?pg=transparencia#!/
Teófilo Otoni	;	https://transparencia.teofilootoni.mg.gov.br/
Barbacena	;	http://barbacena.mg.gov.br/transparencia/
Sabará	;	https://sabara.supernova.com.br:8090/contaspublicas/
Varginha	;	https://leideacesso.etransparencia.com.br/varginha.prefeitura.mg/TDAPortalClient.aspx?414
Vespasiano	;	http://esic.vespasiano.mg.gov.br/Home/Index/
Conselheiro Lafaiete	;	http://conselheirolafaiete.mg.gov.br/v1/
Itabira	;	http://transparencia.itabira.mg.gov.br:8080/pronimtb/
Araguari	;	http://e.araguari.mg.gov.br:8080/portalcidadao/#efb33c382dcf9e4ae2294337ce2a566034ee25478c90493e56f55878a4d19d547154abb93a539ca141901243121b0442f68667740d76583a9b6fc842805a701255f50abffb83548323feb3d4a215dcba05fc4b5b868699999c1d78af95bbbed2ae7ab27d940f9f7a8b2debb75557ba1cd7f6303c3be5a0edaecf72a00208c722773c5ec1c75725b2
Ubá	;	https://transparencia.uba.mg.gov.br/
Passos	;	https://transparencia.passos.mg.gov.br/
Coronel Fabriciano	;	http://sistemas.fabriciano.mg.gov.br/portalcidadao/#efb33c382dcf9e4ae2294337ce2a566034ee25478c90493e56f55878a4d19d547154abb93a539ca141901243121b0442f68667740d76583a9b6fc842805a701255f50abffb83548323feb3d4a215dcba05fc4b5b868699999c1d78af95bbbed2ae7ab27d940f9f7a8b2debb75557ba1cd7f6303c3be5a0edaecf72a00208c722773c5ec1c75725b2
Muriaé	;	http://transparencia.muriae.mg.gov.br/
Araxá	;	http://201.62.57.11:8445/transparencia/
Nova Serrana	;	https://transparencia.novaserrana.mg.gov.br/servidores-por-nomes
Ituiutaba	;	https://www.ituiutaba.mg.gov.br/t/servicos/portal-da-transparencia
Lavras	;	http://187.60.128.132:8082/portalcidadao/#efb33c382dcf9e4ae2294337ce2a566034ee25478c90493e56f55878a4d19d547154abb93a539ca141901243121b0442f68667740d76583a9b6fc842805a701255f50abffb83548323feb3d4a215dcba05fc4b5b868699999c1d78af95bbbed2ae7ab27d940f9f7a8b2debb75557ba1cd7f6303c3be5a0edaecf72a00208c722773c5ec1c75725b2
Itajubá	;	http://www.itajuba.mg.gov.br/servicospmi/portal-da-transparencia/
Nova Lima	;	https://novalima.mg.gov.br/portal-transparencia
Pará de Minas	;	https://transparencia.parademinas.mg.gov.br/servidores
Paracatu	;	http://200.149.134.10/portalcidadao/#efb33c382dcf9e4ae2294337ce2a566034ee25478c90493e56f55878a4d19d547154abb93a539ca141901243121b0442f68667740d76583a9b6fc842805a701255f50abffb83548323feb3d4a215dcba05fc4b5b868699999c1d78af95bbbed2ae7ab27d940f9f7a8b2debb75557ba1cd7f6303c3be5a0edaecf72a00208c722773c5ec1c75725b2
Itaúna	;	https://www.itauna.mg.gov.br/portal/transparencia
Caratinga	;	https://www.caratinga.mg.gov.br/transparencia
Patrocínio	;	http://735c07fc277d.sn.mynetname.net:8085/
Manhuaçu	;	https://manhuacu-mg.portaltp.com.br/
Timóteo	;	https://transparencia.timoteo.mg.gov.br/
São João del Rei	;	http://ptn.saojoaodelrei.mg.gov.br/
Unaí	;	http://201.59.14.108:8080/portalcidadao/#efb33c382dcf9e4ae2294337ce2a566034ee25478c90493e56f55878a4d19d547154abb93a539ca141901243121b0442f68667740d76583a9b6fc842805a701255f50abffb83548323feb3d4a215dcba05fc4b5b868699999c1d78af95bbbed2ae7ab27d940f9f7a8b2debb75557ba1cd7f6303c3be5a0edaecf72a00208c722773c5ec1c75725b2
Curvelo	;	http://amfcorrea.ddns.net/pmAgilNET/Default.aspx
Alfenas	;	http://transparencia.alfenas.mg.gov.br/
João Monlevade	;	https://portaltransparenciajm.portaltp.com.br/
Três Corações	;	https://trescoracoes-mg.portaltp.com.br/
Viçosa	;	https://transparencia.vicosa.mg.gov.br/
Cataguases	;	http://cataguases.mg.gov.br.gestormunicipal.online/transparencia/home/
Ouro Preto	;	https://ouropreto.mg.gov.br/transparencia/
Janaúba	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=PMJanauba
Esmeraldas	;	https://www.esmeraldas.mg.gov.br/acesso-a-informacao
São Sebastião do Paraíso	;	https://transparencia.ssparaiso.mg.gov.br/servidores
Januária	;	https://januaria-mg.portaltp.com.br/
Formiga	;	https://e-gov.betha.com.br/transparencia/01037-108/recursos.faces?mun=IOP41QJty3XGuARkGMa-QUl3uQBEf__9
Lagoa Santa	;	https://portalcidadao.lagoasanta.mg.gov.br/portalcidadao/#efb33c382dcf9e4ae2294337ce2a566034ee25478c90493e56f55878a4d19d547154abb93a539ca141901243121b0442f68667740d76583a9b6fc842805a701255f50abffb83548323feb3d4a215dcba05fc4b5b868699999c1d78af95bbbed2ae7ab27d940f9f7a8b2debb75557ba1cd7f6303c3be5a0edaecf72a00208c722773c5ec1c75725b2
Pedro Leopoldo	;	http://pedroleopoldo.mg.gov.br/?page_id=5139
Mariana	;	http://www.transparencia.mariana.mg.gov.br/
Frutal	;	https://www.frutal.mg.gov.br/transparencia/
Ponte Nova	;	https://transparencia.pontenova.mg.gov.br/
Três Pontas	;	https://www.trespontas.mg.gov.br/transparencia
Pirapora	;	http://177.36.214.150/ecidade_transparencia/main
São Francisco	;	https://www.prefeituradesaofrancisco.mg.gov.br/transparencia/
Congonhas	;	https://www.congonhas.mg.gov.br/index.php/portal-transparencia-prefeitura/
Campo Belo	;	https://campobelo.atende.net/?pg=transparencia#!/
Lagoa da Prata	;	https://e-gov.betha.com.br/transparencia/recursos.faces?mun=-z4rr_vkTZDRWSka3BHKbPr5Ak5IL3PQ
Leopoldina	;	https://www.leopoldina.mg.gov.br/transparencia
Itabirito	;	http://189.80.147.171:8090/contaspublicas/
Guaxupé	;	https://ts.guaxupe.mg.gov.br/portalcidadao/
Bom Despacho	;	https://www.bomdespacho.mg.gov.br/transparencia/
Bocaiúva	;	http://www.bocaiuva.mg.gov.br/transparencia.html
Monte Carmelo	;	http://735c07fc277d.sn.mynetname.net:8072/
Diamantina	;	http://transparencia.diamantina.mg.gov.br/
João Pinheiro	;	http://novosite.fjp.mg.gov.br/transparencia/
Santos Dumont	;	http://www.mgcidades.com.br/index?option=com_contpubl&idcid=316070&mgcidades=1&
São Lourenço	;	https://pm-slourenco.publicacao.siplanweb.com.br/
Caeté	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=CamCaete
Igarapé	;	http://sistemas.igarape.mg.gov.br:8080/portalcidadao/#efb33c382dcf9e4ae2294337ce2a566034ee25478c90493e56f55878a4d19d547154abb93a539ca141901243121b0442f68667740d76583a9b6fc842805a701255f50abffb83548323feb3d4a215dcba05fc4b5b868699999c1d78af95bbbed2ae7ab27d940f9f7a8b2debb75557ba1cd7f6303c3be5a0edaecf72a00208c722773c5ec1c75725b2
Santa Rita do Sapucaí	;	http://www.transparenciafacil.com.br/0202202
Visconde do Rio Branco	;	http://pt.viscondedoriobranco.mg.gov.br/
Machado	;	http://www.transparenciafacil.com.br/0178602
Almenara	;	https://almenara-mg.portaltp.com.br/
Oliveira	;	https://oliveira.atende.net/?pg=transparencia#!/
Salinas	;	http://lai.memory.com.br/entidades/login/9D2D8L
Andradas	;	http://server.andradas.mg.gov.br:8080/portalcidadao/#075f539f0b7223f116d2c85c4ce1b1752fccb0db1fd92284312b33310fb199ef6050e9373e0f36365cbb7737a0e49e582e657146a648fd13734b1e4257ce26784038c1e951f7b9d45a9533bb5ae039796f7ff47d31979ce5
Brumadinho	;	http://transparencia.brumadinho.mg.gov.br/
Nanuque	;	https://nanuque-mg.portaltp.com.br/
Arcos	;	http://177.71.169.183/pronimtb/
Boa Esperança	;	https://e-gov.betha.com.br/transparencia/01037-108/recursos.faces
Ouro Branco	;	https://e-gov.betha.com.br/transparencia/01037-108/recursos.faces?mun=tvrMMwtvmbcoC2EP4aprSV8RhpRd-St4
Várzea da Palma	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=PMVarzeaDaPalma
Iturama	;	http://200.233.183.165:8444/transparencia/
Jaíba	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=JaibaPM
Matozinhos	;	http://lai.memory.com.br/entidades/login/9BHSQH
Capelinha	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=PMCapelinha
Porteirinha	;	http://lai.memory.com.br/entidades/login/9CJZDH
Extrema	;	https://extrema-mg.portaltp.com.br/
Araçuaí	;	https://www.aracuai.mg.gov.br/transparencia
São Gotardo	;	http://transparencia.saogotardo.mg.gov.br/
Além Paraíba	;	https://transparencia.alemparaiba.mg.gov.br/
Santana do Paraíso	;	https://www.santanadoparaiso.mg.gov.br/transparencia
Itamarandiba	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=Itamarandiba
Piumhi	;	http://lai.memory.com.br/entidades/login/9CHJUT
Guanhães	;	http://transparencia.guanhaes.mg.gov.br/
Taiobeiras	;	https://taiobeiras-mg.portaltp.com.br/
Ouro Fino	;	https://ouro.atende.net/?pg=transparencia#!/
Sarzedo	;	https://e-gov.betha.com.br/transparencia/01037-108/recursos.faces?mun=RAs2ILPR6DTL39dg46ij7aulcbJ9yhp8
Carangola	;	https://www.carangola.mg.gov.br/index.php/home/transparencia
Barão de Cocais	;	https://www.baraodecocais.mg.gov.br/transparencia
Três Marias	;	https://www.tresmarias.mg.gov.br/transparencia
Brasília de Minas	;	https://portal.brasiliademinas.mg.gov.br/transparencia/
São Joaquim de Bicas	;	http://187.109.4.146:10000/portalcidadao/#075f539f0b7223f116d2c85c4ce1b1752fccb0db1fd92284312b33310fb199ef6050e9373e0f36365cbb7737a0e49e582e657146a648fd13734b1e4257ce26784038c1e951f7b9d45a9533bb5ae039796f7ff47d31979ce5
Pompéu	;	https://transparencia.pompeu.mg.gov.br/transparencia
Espinosa	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=Espnsa
Santa Bárbara	;	https://transparencia.santabarbara.mg.gov.br/
Minas Novas	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=MinasNov
Mateus Leme	;	https://portaltransp.com.br/?data=pmtl
Novo Cruzeiro	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=pmnovocruzeiro
Rio Pardo de Minas	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=PrefRioPMinas
Carmo do Paranaíba	;	http://sistemas.carmodoparanaiba.mg.gov.br:8444/transparencia/
Cambuí	;	https://transparencia.prefeituradecambui.mg.gov.br/transparencia
Cláudio	;	https://www.claudio.mg.gov.br/portal/transparencia
Campos Gerais	;	http://transparencia.camposgerais.mg.gov.br/
Santo Antônio do Monte	;	https://e-gov.betha.com.br/transparencia/01037-132/recursos.faces?mun=M8eLJVYzPQn91SYblV3vM-BVLm_DXL3R
Elói Mendes	;	https://eloimendes.mg.gov.br/portal-da-transparencia/
Buritizeiro	;	http://www.cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=Buritizeiro
Pitangui	;	http://lai.memory.com.br/entidades/login/9CHA9H
Coromandel	;	http://sistemasonline.coromandel.mg.gov.br:8083/transparencia/
Conceição das Alagoas	;	http://187.72.75.161:8444/transparencia/
Prata	;	http://200.233.191.145/portalcidadao/#df1b1a7c7b2a290bcb31e32771e610784662739a88807c0dacac58ede5f391a7530e299dc302d611ee73cb143fc22eaf93592e53e7b5bdb01b00a0b8d28dae460c141dd2ff83412e4dc1c31b16b25f33144a9e5620ea73b13f5bc1c59411d98439ad226e8af03840603796067d87afe130812cf3de24982d0e306f9e61e764e5
Mantena	;	https://e-gov.betha.com.br/transparencia/01037-108/recursos.faces?mun=Tqd1IxCt-iyORmVL86LYju2Df4QzIBma
Mutum	;	http://lai.memory.com.br/entidades/login/9BQNHD
Juatuba	;	https://portaltransp.com.br/?data=pjtb
Nepomuceno	;	https://e-gov.betha.com.br/transparencia/01037-108/recursos.faces
Belo Oriente	;	https://www.belooriente.mg.gov.br/transparencia
Coração de Jesus	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=CoracaoDeJes
São João Nepomuceno	;	https://www.sjnepomuceno.mg.gov.br/transparencia
Francisco Sá	;	http://www.cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=FranciscoSa
Sacramento	;	https://e-gov.betha.com.br/transparencia/01037-108/recursos.faces?mun=2PUu6Ie8y0M=
Jacutinga	;	https://www.jacutinga.mg.gov.br/2021-2024/index.php/transparencia
Carandaí	;	http://www.adpmnet.com.br/index.php?option=com_contpubl&idorg=495&tpform=1;http://ptn.hospital.carandai.mg.gov.br/
São Gonçalo do Sapucaí	;	https://www.municipalnet.com.br/index/?uid=sao-goncalo-do-sapucai
Jequitinhonha	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=Jequitinhonha
Tupaciguara	;	http://transparencia.tupaciguara.mg.gov.br:8444/transparencia/
Ibiá	;	http://lai.memory.com.br/entidades/login/9AEG3L
Aimorés	;	https://www.aimores.mg.gov.br/transparencia
São João da Ponte	;	https://saojoaodaponte.mg.gov.br/transparencia
Espera Feliz	;	https://esperafeliz-mg.portaltp.com.br
Buritis	;	http://www.adpmnet.com.br/index.php?option=com_contpubl&idorg=104&tpform=1
Paraopeba	;	https://www.paraopeba.mg.gov.br/transparencia
Pedra Azul	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=PedraAzul
Inhapim	;	https://www.inhapim.mg.gov.br/transparencia
Bambuí	;	https://www.bambui.mg.gov.br/transparencia
Monte Sião	;	https://montesiao-mg.portaltp.com.br/
São José da Lapa	;	http://187.86.245.10:8083/portalcidadao/#efb33c382dcf9e4ae2294337ce2a566034ee25478c90493e56f55878a4d19d547154abb93a539ca141901243121b0442f68667740d76583a9b6fc842805a701255f50abffb83548323feb3d4a215dcba05fc4b5b868699999c1d78af95bbbed2ae7ab27d940f9f7a8b2debb75557ba1cd7f6303c3be5a0edaecf72a00208c722773c5ec1c75725b2
Raul Soares	;	https://www.raulsoares.mg.gov.br/transparencia
Corinto	;	http://lai.memory.com.br/entidades/login/99EZ01
Caraí	;	https://www.carai.mg.gov.br/transparencia
São João do Paraíso	;	https://saojoaodoparaiso-mg.portaltp.com.br/
Abaeté	;	http://www.adpmnet.com.br/index.php?option=com_contpubl&submenu=1&cnpj=18296632000100&idreg=&tpformtab=jos_coputvcb1&tpformpdf=51&tpform=2&idorg=96&dsorg=Prefeitura%20Municipal%20de%20Abaet%C3%A9&dsufe=Estado%20de%20Minas%20Gerais&brasao=P310020.GIF&titulo=Remunera%C3%A7%C3%A3o%20Mensal%20dos%20Servidores%20P%C3%BAblicos&idtpc=0&nome_mat=1&nao_proventos=0&nao_descontos=0
Itambacuri	;	https://itambacuri-mg.portaltp.com.br/
Conselheiro Pena	;	https://www.conselheiropena.mg.gov.br/transparencia
Manhumirim	;	http://lai.memory.com.br/entidades/login/9BD0YH
Carmo do Cajuru	;	https://e-gov.betha.com.br/transparencia/01037-108/recursos.faces?mun=_i5DCEkGwpoaJI9YULdVken_zmagbH4A
Camanducaia	;	http://www.camanducaia.mg.gov.br/transparencia/
Itapecerica	;	http://www.adpmnet.com.br/index.php?option=com_contpubl&idorg=121&tpform=1
Caxambu	;	http://170.254.192.42:8080/portalcidadao/#df1b1a7c7b2a290bcb31e32771e610784662739a88807c0dacac58ede5f391a7530e299dc302d611ee73cb143fc22eaf93592e53e7b5bdb01b00a0b8d28dae460c141dd2ff83412e4dc1c31b16b25f33144a9e5620ea73b13f5bc1c59411d98439ad226e8af03840603796067d87afe130812cf3de24982d0e306f9e61e764e5
Monte Santo de Minas	;	https://transparencia.montesantodeminas.mg.gov.br/
Paraguaçu	;	https://e-gov.betha.com.br/transparencia/01037-108/recursos.faces?mun=GSJbAPBc7Hw=
Perdões	;	http://lai.memory.com.br/entidades/login/9CCNMT
Carmo do Rio Claro	;	http://177.11.86.115:8079/transparencia/
Monte Alegre de Minas	;	http://187.72.215.252:8080/dadosweb/loginWeb.jsp?execobj=XXPW20200
Paraisópolis	;	https://www.saaeparaisopolis.mg.gov.br/transparencia
Itaobim	;	https://www.itaobim.mg.gov.br/transparencia
Campestre	;	http://lai.memory.com.br/entidades/login/98M0P9
Serro	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=PMSerro
Monte Azul	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=MonteAzul
Medina	;	https://www.medina.mg.gov.br/transparencia
Lambari	;	http://lambari-mg.portaltp.com.br/
Barroso	;	http://pt.barroso.mg.gov.br/
Vazante	;	https://www.vazante.mg.gov.br/
Muzambinho	;	https://www.muzambinho.mg.gov.br/transparencia
Padre Paraíso	;	https://www.padreparaiso.mg.gov.br/transparencia
Jaboticatubas	;	https://jaboticatubas-mg.portaltp.com.br/
Turmalina	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=Turmalina
Divino	;	https://divino.mg.gov.br/transparencia/index.php
Lajinha	;	https://lajinha-mg.portaltp.com.br/
Ipanema	;	http://lai.memory.com.br/entidades/login/9AJM11
Alpinópolis	;	http://alpinopolisportaltransparencia.portalfacil.com.br/principal
Campina Verde	;	http://pmcverde.horusdm.com.br/transparencia
Santa Vitória	;	http://portal.santavitoria.mg.gov.br:9191/portalcidadao/#075f539f0b7223f116d2c85c4ce1b1752fccb0db1fd92284312b33310fb199ef6050e9373e0f36365cbb7737a0e49e582e657146a648fd13734b1e4257ce26784038c1e951f7b9d45a9533bb5ae039796f7ff47d31979ce5
Simonésia	;	https://simonesia-mg.portaltp.com.br/
Presidente Olegário	;	http://lai.memory.com.br/entidades/login/9CND71
Borda da Mata	;	http://www.transparenciafacil.com.br/0142602
Carmópolis de Minas	;	https://transparencia.carmopolisdeminas.mg.gov.br/
Varzelândia	;	https://varzelandia.mg.gov.br/?page_id=197
Águas Formosas	;	http://aguasformosas-mg.portaltp.com.br/
Baependi	;	http://www.baependi.mg.gov.br/transparencia/
Guaranésia	;	https://e-gov.betha.com.br/transparencia/01037-108/recursos.faces
Matipó	;	https://matipo.mg.gov.br/transparencia/
Ervália	;	http://pt.ervalia.mg.gov.br/
Carlos Chagas	;	https://portaltransp.com.br/?data=pclc
Malacacheta	;	http://www.contasabertas.inf.br/abre/6364d3f0f495b6ab9dcf8d3b5c6e0b01
Ipaba	;	https://www.ipaba.mg.gov.br/transparencia
Santo Antônio do Amparo	;	https://portaltransp.com.br/?data=psaa
Manga	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=Manga
Luz	;	https://e-gov.betha.com.br/transparencia/01037-108/recursos.faces?mun=e7QgmIkky-ywyWyWbpGr7_da3er16J-5
Itacarambi	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=PMItacarambi
Ladainha	;	https://ladainha-mg.portaltp.com.br/
Fronteira	;	http://www.horusdm.com.br/digital/index/entidade/id/5
Lagoa Formosa	;	http://transparencia.lagoaformosa.mg.gov.br:8444/transparencia/
Rio Pomba	;	https://transparencia.riopomba.mg.gov.br/transparencia
Arinos	;	http://www.adpmnet.com.br/index.php?option=com_contpubl&idorg=236&tpform=1
Conceição do Mato Dentro	;	http://lai.memory.com.br/entidades/login/999RZ1
Cássia	;	http://cassiaportaltransparencia.portalfacil.com.br/
Piranga	;	https://www.piranga.mg.gov.br/transparencia
Bom Sucesso	;	lai.memory.com.br/entidades/login/98CSD1
Nova Era	;	https://www.novaera.mg.gov.br/transparencia
Peçanha	;	https://www.pecanha.mg.gov.br/transparencia
Resplendor	;	http://transparencia.resplendor.mg.gov.br/
São Domingos do Prata	;	https://saodomingosdoprata-mg.portaltp.com.br/
Urucuia	;	http://www.urucuia.mg.gov.br/site/index.php/transparencia
Poço Fundo	;	http://191.252.56.191:9021/transparencia/
Nova Resende	;	https://www.novaresende.mg.gov.br/transparencia/portal-da-transparencia
Lima Duarte	;	https://pm-lduarte.publicacao.siplanweb.com.br/
Campanha	;	https://www.campanha.mg.gov.br/index.php?option=com_content&view=article&id=1379&Itemid=228
Tocantins	;	https://tocantins.mg.gov.br/transparencia/
Poté	;	https://pote-mg.portaltp.com.br/
Brasilândia de Minas	;	https://www.brasilandiademinas.mg.gov.br/
Raposos	;	https://e-gov.betha.com.br/transparencia/01037-108/recursos.faces?mun=b0yqVbCtMlW1gxPNyOGym6Op7A3j0DxJ
Passa Quatro	;	http://transparencia.passaquatro.mg.gov.br/
Santa Margarida	;	http://lai.memory.com.br/entidades/login/9D5589
Capinópolis	;	http://189.112.90.234:8089/portalcidadao/#df1b1a7c7b2a290bcb31e32771e610784662739a88807c0dacac58ede5f391a7530e299dc302d611ee73cb143fc22eaf93592e53e7b5bdb01b00a0b8d28dae460c141dd2ff83412e4dc1c31b16b25f33144a9e5620ea73b13f5bc1c59411d98439ad226e8af03840603796067d87afe130812cf3de24982d0e306f9e61e764e5
Perdizes	;	http://138.118.240.126:8444/transparencia/
Itaú de Minas	;	http://177.221.27.2:8079/transparencia/
Grão Mogol	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=GrMogl
São João Evangelista	;	http://saojoaoevangelista-mg.portaltp.com.br/
Papagaios	;	http://lai.memory.com.br/entidades/login/9C3JAL
Itamonte	;	http://transparencia.itamonte.mg.gov.br/
Nova Ponte	;	http://portal.novaponte.mg.gov.br:8444/transparencia/
Sabinópolis	;	https://www.sabinopolis.mg.gov.br/transparencia
Campos Altos	;	http://transparencia.camposaltos.mg.gov.br/
Joaíma	;	http://lai.memory.com.br/entidades/login/9B2AS5
Cruzília	;	https://pm-cruzilia.publicacao.siplanweb.com.br/
Mário Campos	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=MarioCampos
Chapada do Norte	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=chapadanorte
Felixlândia	;	http://felixlandia.mg.gov.br/Transparencia/
Itanhandu	;	http://179.109.2.67:8080/portalcidadao/#efb33c382dcf9e4ae2294337ce2a566034ee25478c90493e56f55878a4d19d547154abb93a539ca141901243121b0442f68667740d76583a9b6fc842805a701255f50abffb83548323feb3d4a215dcba05fc4b5b868699999c1d78af95bbbed2ae7ab27d940f9f7a8b2debb75557ba1cd7f6303c3be5a0edaecf72a00208c722773c5ec1c75725b2
Entre Rios de Minas	;	http://pt.entreriosdeminas.mg.gov.br/Principal
Itapagipe	;	http://pmitapagipe.horusdm.com.br/transparencia
Capitão Enéas	;	http://transparencia.contassconsultoria.com.br/pmcapitaoeneas/
Alvinópolis	;	https://www.alvinopolis.mg.gov.br/transparencia/portal-da-transparencia
Areado	;	https://areado.mg.gov.br/contas/
Miraí	;	http://www.mirai.mg.gov.br/site/transparencia/TransparenciaMunicipioP.php
Itinga	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=Itinga
Botelhos	;	http://botelhos.mg.gov.br/index.php?option=com_content&view=article&id=1075&Itemid=15
Bom Jesus do Galho	;	https://www.bomjesusdogalho.mg.gov.br/transparencia
Candeias	;	https://www.candeias.mg.gov.br/portal/transparencia
Montalvânia	;	https://montalvania-mg.portaltp.com.br/
Carmo de Minas	;	https://pm-cminas.publicacao.siplanweb.com.br/
Santa Maria do Suaçuí	;	https://pmsmsuacui-transparencia.gpecloud.com.br/
Bicas	;	https://www.bicas.mg.gov.br/transparencia
Caldas	;	https://caldas-mg.portaltp.com.br/
Matias Barbosa	;	https://www.matiasbarbosa.mg.gov.br/transparencia
Alterosa	;	https://e-gov.betha.com.br/transparencia/01037-108/recursos.faces
Brazópolis	;	http://www.adpmnet.com.br/index.php?option=com_contpubl&idorg=101&tpform=1
Rio Piracicaba	;	https://riopiracicaba-mg.portaltp.com.br/
Tarumirim	;	https://www.tarumirim.mg.gov.br/transparencia
Guapé	;	https://transparencia.guape.mg.gov.br/transparencia
Astolfo Dutra	;	https://pm-adutra.publicacao.siplanweb.com.br/
Maria da Fé	;	https://www.mariadafe.mg.gov.br/transparencia
Cabo Verde	;	https://www.caboverde.mg.gov.br/transparencia/portal-da-transparencia
Santa Juliana	;	http://201.62.59.250:8080/portalcidadao/#efb33c382dcf9e4ae2294337ce2a566034ee25478c90493e56f55878a4d19d547154abb93a539ca141901243121b0442f68667740d76583a9b6fc842805a701255f50abffb83548323feb3d4a215dcba05fc4b5b868699999c1d78af95bbbed2ae7ab27d940f9f7a8b2debb75557ba1cd7f6303c3be5a0edaecf72a00208c722773c5ec1c75725b2
Ibiraci	;	http://ibiraci.mg.gov.br/portal-da-transparencia/
Virgem da Lapa	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=VirgemLapa
Água Boa	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=AguaBoa
Chapada Gaúcha	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=ChapadaGaucha
Conceição do Rio Verde	;	http://conceicaodorioverde.mg.gov.br/portal-da-transparencia/
Mirabela	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=mirabela
Rio Casca	;	https://e-gov.betha.com.br/transparencia/01037-108/recursos.faces
Águas Vermelhas	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=PMAguasVermelhas
Dores do Indaiá	;	http://177.37.100.250:8080/portalcidadao/#075f539f0b7223f116d2c85c4ce1b1752fccb0db1fd92284312b33310fb199ef6050e9373e0f36365cbb7737a0e49e582e657146a648fd13734b1e4257ce26784038c1e951f7b9d45a9533bb5ae039796f7ff47d31979ce5
Abre Campo	;	http://abrecampo-mg.portaltp.com.br/
Martinho Campos	;	http://lai.memory.com.br/entidades/login/9BG219
Itaguara	;	https://e-gov.betha.com.br/transparencia/01037-108/recursos.faces?mun=iShg8dP1D5cMGdQ4R1BH8HYZRmlXk41O
Monte Belo	;	https://www.montebelo.mg.gov.br/transparencia
São João das Missões	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=SaoJoaoDasMiss
Lagoa Dourada	;	http://pt.lagoadourada.mg.gov.br/
Ataléia	;	https://ataleia.mg.gov.br/transparencia
Rio Vermelho	;	https://riovermelho.mg.gov.br/transparencia/
Cambuquira	;	https://e-gov.betha.com.br/transparencia/01037-108/recursos.faces
Mar de Espanha	;	https://www.mardeespanha.com/transparencia
Cristais	;	http://transparencia.cristais.mg.gov.br
Itaipé	;	http://www.itaipe.mg.gov.br/transparencia/
Ubaí	;	https://ubai.mg.gov.br/portal-da-transparencia/
Ubaporanga	;	https://www.ubaporanga.mg.gov.br/transparencia
Mato Verde	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=MatoVerde
São Gonçalo do Pará	;	https://www.saogoncalodopara.mg.gov.br/transparencia
Jequeri	;	https://www.jequeri.mg.gov.br/transparencia
Ilicínea	;	http://portal-transparencia.portyx.com.br/?orgao=20
São Geraldo	;	http://pt.saogeraldo.mg.gov.br/
São Romão	;	http://cidadesmg.com.br/portaltransparencia/faces/user/FDiariasViagem.xhtml?Param=SaoRomao
Jacinto	;	https://jacinto-mg.portaltp.com.br/consultas/pessoal/servidores.aspx
Rio Paranaíba	;	http://prefriopara.ddns.net:8444/transparencia/paginas/publico/faleConosco/homeFaleConosco.xhtml
Setubinha	;	http://www.cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=Setubinha
Itanhomi	;	https://transparencia.itanhomi.mg.gov.br/servidores/
Andrelândia	;	https://andrelandia.mg.gov.br/site/transparencia/
Carmo da Cachoeira	;	https://www.municipalnet.com.br/index/?uid=carmo-da-cachoeira
Canápolis	;	http://transparencia.canapolis.mg.gov.br:8080/portalcidadao/#efb33c382dcf9e4ae2294337ce2a566034ee25478c90493e56f55878a4d19d547154abb93a539ca141901243121b0442f68667740d76583a9b6fc842805a701255f50abffb83548323feb3d4a215dcba05fc4b5b868699999c1d78af95bbbed2ae7ab27d940f9f7a8b2debb75557ba1cd7f6303c3be5a0edaecf72a00208c722773c5ec1c75725b2
Planura	;	https://e-gov.betha.com.br/transparencia/01037-108/recursos.faces
Ponto dos Volantes	;	https://www.pontodosvolantes.mg.gov.br/transparencia
Pedras de Maria da Cruz	;	https://www.pedrasdemariadacruz.mg.gov.br/Web/transparencia/
Icaraí de Minas	;	http://icaraideminas.mg.gov.br/portal-da-transparencia/
Congonhal	;	https://www.municipalnet.com.br/index/?uid=congonhal
Berilo	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=Berilo
Gouveia	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=Gouveia
Teixeiras	;	https://pm-teixeiras.publicacao.siplanweb.com.br/
Campo do Meio	;	https://www.campodomeio.mg.gov.br/portal/transparencia
Santo Antônio do Jacinto	;	https://www.santoantoniodojacinto.mg.gov.br/transparencia
Conceição dos Ouros	;	http://pt.conceicaodosouros.mg.gov.br/Folha
Caetanópolis	;	http://lai.memory.com.br/entidades/login/98YLRD
Serra do Salitre	;	http://187.62.86.129:8444/transparencia/
São João do Manhuaçu	;	https://transparencia.saojoaodomanhuacu.mg.gov.br/
Cachoeira de Minas	;	http://www.transparenciafacil.com.br/servidores-por-nomes/0144301
Itabirinha	;	https://www.itabirinha.mg.gov.br/transparencia
Perdigão	;	http://lai.memory.com.br/entidades/login/9CC4C5
Resende Costa	;	http://pt.resendecosta.mg.gov.br/
Carmo da Mata	;	https://www.carmodamata.mg.gov.br/transparencia
Antônio Carlos	;	http://pt.municipioantoniocarlos.mg.gov.br/
Estiva	;	http://www.transparenciafacil.com.br/0161201
Porto Firme	;	https://www.portofirme.mg.gov.br/transparencia/portal-da-transparencia
Eugenópolis	;	https://www.eugenopolis.mg.gov.br/transparencia/
Bonito de Minas	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=BonitoDeMinas
Pedralva	;	https://www.pedralva.mg.gov.br/pessoal
Matias Cardoso	;	http://lai.memory.com.br/entidades/login/9BH3QH
Itatiaiuçu	;	https://e-gov.betha.com.br/transparencia/01037-108/recursos.faces?mun=l_xE2SVOBCE=
Engenheiro Caldas	;	https://www.engenheirocaldas.mg.gov.br/transparencia
Divisópolis	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=Divisopolis
Fervedouro	;	https://pm-fervedouro.publicacao.siplanweb.com.br/
Iapu	;	https://transparencia.iapu.mg.gov.br/
Bueno Brandão	;	http://buenobrandao.mg.gov.br/novosite/portal-da-transparencia-2/
Alto Rio Doce	;	https://e-gov.betha.com.br/transparencia/01037-108/recursos.faces?mun=ZH0vSwlq0OOmRKGmYfRhU5Cl-xRrhAqO
São Tiago	;	http://ptn.saotiago.mg.gov.br/
São Gonçalo do Rio Abaixo	;	https://www.saogoncalo.mg.gov.br/transparencia
Igaratinga	;	http://igaratinga.mg.gov.br/conteudo/transparencia
Santa Maria de Itabira	;	http://santamariadeitabiratp.portalfacil.com.br/transparencia
Jordânia	;	https://www.jordania.mg.gov.br/transparencia
Piraúba	;	http://www.transparenciafacil.com.br/0193802
Arceburgo	;	https://www.arceburgo.mg.gov.br/category/transparencia/
Novo Oriente de Minas	;	https://www.novoorientedeminas.mg.gov.br/transparencia
Miradouro	;	https://prefeitura24horas.online/_transparencia/home/
Pirapetinga	;	http://www.pirapetinga.mg.gov.br/transparencia/
Mercês	;	http://www.merces.mg.gov.br/portal/transparencia-portal.php
Prudente de Morais	;	http://lai.memory.com.br/entidades/login/9CZ1H1
Juruaia	;	https://www.juruaia.mg.gov.br/portal-transparencia
Bom Repouso	;	http://www.transparenciafacil.com.br/servidores-por-nomes/0142101
Delta	;	http://www.delta.mg.gov.br/portal-da-transparencia/
Recreio	;	http://www.mgcidades.com.br/index.php?option=com_contpubl&idcid=315410&mgcidades=1
Virginópolis	;	https://pmvgp.portaldatransparencia.info/
Senhora dos Remédios	;	https://pm-sremedios.publicacao.siplanweb.com.br/
Buenópolis	;	http://lai.memory.com.br/entidades/login/98GH6H
Urucânia	;	https://www.urucania.mg.gov.br/transparencia
Centralina	;	http://centralinamg.ddns.net:8444/transparencia/
Francisco Badaró	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=FrancBandr
Guaraciaba	;	http://www.transparenciafacil.com.br/0165702
Rio Acima	;	http://pt.prefeiturarioacima.mg.gov.br/
Ninheira	;	https://ninheira-mg.portaltp.com.br/
Conceição da Aparecida	;	http://pt.prefeiturarioacima.mg.gov.br/
Bela Vista de Minas	;	https://www.belavistademinas.mg.gov.br/transparencia
Cristina	;	https://pm-cristina.publicacao.siplanweb.com.br/
Rubim	;	https://rubim-mg.portaltp.com.br/
Itamogi	;	https://itamogi.mg.gov.br/transparencia/
Dores de Campos	;	http://pt.doresdecampos.mg.gov.br/Folha
Ipuiúna	;	http://www.transparenciafacil.com.br/0169601
São Sebastião do Maranhão	;	https://www.saosebastiaodomaranhao.mg.gov.br/transparencia
Carneirinho	;	http://transparencia.carneirinho.mg.gov.br:8090/portalcidadao/#efb33c382dcf9e4ae2294337ce2a566034ee25478c90493e56f55878a4d19d547154abb93a539ca141901243121b0442f68667740d76583a9b6fc842805a701255f50abffb83548323feb3d4a215dcba05fc4b5b868699999c1d78af95bbbed2ae7ab27d940f9f7a8b2debb75557ba1cd7f6303c3be5a0edaecf72a00208c722773c5ec1c75725b2
Coroaci	;	https://www.coroaci.mg.gov.br/transparencia
Ferros	;	http://ferros.mg.gov.br/portal/?Link=Home
Itapeva	;	https://e-gov.betha.com.br/transparencia/01037-108/recursos.faces?mun=5QecS5u6hOnx7T0IfpzfTXDJDYqFSDUS
Capim Branco	;	http://capimbranco-mg.portaltp.com.br/
Lontra	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=PmLontra
Frei Inocêncio	;	https://transparencia.freiinocencio.mg.gov.br/
Paula Cândido	;	http://paulacandido.mg.gov.br/portal/transparencia.php
Formoso	;	https://www.monteformoso.mg.gov.br/servidores-por-nomes
Lagoa Grande	;	http://lai.memory.com.br/financeiro/9B7001
Riacho dos Machados	;	http://lai.memory.com.br/entidades/login/9CQPAD
Açucena	;	https://www.acucena.mg.gov.br/transparencia
Cachoeira de Pajeú	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=CachoeiraPajeu
Carbonita	;	https://carbonita-mg.portaltp.com.br/
Verdelândia	;	http://www.verdelandia.mg.gov.br/portal-da-transparencia/
Antônio Dias	;	https://www.antoniodias.mg.gov.br/transparencia
Caputira	;	http://www.transparenciafacil.com.br/0147902
Araújos	;	http://lai.memory.com.br/entidades/login/980B7H
Coronel Murta	;	https://pmcoronelmurta-transparencia.gpecloud.com.br/
Coqueiral	;	https://www.municipalnet.com.br/index/?uid=coqueiral
Prados	;	http://pt.prados.mg.gov.br/
Rio Novo	;	https://pm-rionovo.publicacao.siplanweb.com.br/
Santa Rita de Caldas	;	http://www.transparenciafacil.com.br/0201701
Guarani	;	https://pm-guarani.publicacao.siplanweb.com.br/
Cordisburgo	;	https://cordisburgo-mg.portaltp.com.br/
Coluna	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=Coluna
Morada Nova de Minas	;	http://lai.memory.com.br/entidades/login/9BP6DH
Serra dos Aimorés	;	https://pmsa.mg.gov.br/transparencia/
Monsenhor Paulo	;	https://camaramonsenhorpaulo.mg.gov.br/portal-da-transparencia-2/
Santana do Manhuaçu	;	https://santanadomanhuacu-mg.portaltp.com.br/
Virgínia	;	http://transparencia.virginia.mg.gov.br/
Pimenta	;	http://pimenta.mg.gov.br/portalprefeitura/
Capitólio	;	https://www.capitolio.mg.gov.br/comunicado/
Nazareno	;	http://pt.nazareno.mg.gov.br/
Santa Cruz de Minas	;	http://pt.santacruzdeminas.mg.gov.br/Principal
Pratápolis	;	http://pratapolisportaltransparencia.portalfacil.com.br/transparencia
Piranguinho	;	http://www.adpmnet.com.br/index.php?option=com_contpubl&idorg=32&tpform=1
Mata Verde	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=MataVerde
Piedade de Caratinga	;	http://piedadedecaratingaportaltransparencia.portalfacil.com.br/transparencia
Angelândia	;	https://www.angelandia.mg.gov.br/transparencia
Pavão	;	https://www.pavao.mg.gov.br/transparencia
Araponga	;	http://www.transparenciafacil.com.br/0137702
Pocrane	;	https://pocrane-mg.portaltp.com.br/
Martins Soares	;	https://martinssoares-mg.portaltp.com.br/
Ibiaí	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=PmIbiai
Guiricema	;	http://www.transparenciafacil.com.br/0166602
São Gonçalo do Abaeté	;	https://saogoncalodoabaete-mg.portaltp.com.br/
Alto Jequitibá	;	https://transparencia.altojequitiba.mg.gov.br/
Pains	;	http://lai.memory.com.br/entidades/login/9C2BLT
Montezuma	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=Montezuma
Campo Florido	;	http://transparencia.campoflorido.mg.gov.br:8444/transparencia
Santa Bárbara do Leste	;	http://santabarbaradoleste-mg.portaltp.com.br/
Riachinho	;	http://lai.memory.com.br/entidades/login/9CQKE5
Rodeiro	;	https://transparencia.rodeiro.mg.gov.br/
Passa Tempo	;	http://www.transparenciafacil.com.br/0189401
Guimarânia	;	http://portaldatransparencia.guimarania.mg.gov.br/
Delfim Moreira	;	https://transparencia-hd.com.br/?cod_empre=61
Tombos	;	https://transparencia.prefeituratombos.mg.gov.br/
Orizânia	;	https://www.orizania.mg.gov.br/transparencia
Tiradentes	;	http://ptn.tiradentes.mg.gov.br/
Estrela do Sul	;	http://187.44.64.138:8445/transparencia/
Maravilhas	;	http://maravilhasportaltransparencia.portalfacil.com.br/
Japonvar	;	https://japonvar.mg.gov.br/transparencia/
Iguatama	;	http://lai.memory.com.br/entidades/login/9AGU7L
Durandé	;	https://transparencia.durande.mg.gov.br:443/
Baldim	;	http://www.baldim.mg.gov.br/index.php/pt/acesso-a-informacao/transparencia
Senador Firmino	;	https://pm-sfirmino.publicacao.siplanweb.com.br/
São Pedro dos Ferros	;	https://saopedrodosferros-mg.portaltp.com.br/
São Vicente de Minas	;	http://ptn.saovicentedeminas.mg.gov.br/
Curral de Dentro	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=CurralDeDentro
Dionísio	;	https://www.dionisio.mg.gov.br/transparencia
Belo Vale	;	http://pt.belovale.mg.gov.br/
Jenipapo de Minas	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=JenipapoMinas
Jacuí	;	http://www.transparenciafacil.com.br/0173002
Serrania	;	https://www.serrania.mg.gov.br/transparencia/portal-da-transparencia
Cônego Marinho	;	http://pmcmarinho.horusdm.com.br/transparencia
Santana de Pirapama	;	http://lai.memory.com.br/entidades/login/9D701H
Lagamar	;	http://lai.memory.com.br/entidades/login/9B5M09
Divinolândia de Minas	;	http://lai.memory.com.br/entidades/login/99Z70T
Coimbra	;	https://pm-coimbra.publicacao.siplanweb.com.br/
Claro dos Poções	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=ClarDosPces
Limeira do Oeste	;	https://limeiradooeste.mg.gov.br/portal-da-transparencia/
Jequitaí	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=Jequitai
Moema	;	http://www.transparenciafacil.com.br/0182702
Inimutaba	;	https://portaltransp.com.br/?data=pimt
Pintópolis	;	http://cidadesmg.com.br/portaltransparencia/faces/user/FDiariasViagem.xhtml?Param=PMPintopolis
Nova Porteirinha	;	http://www.cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=NovaPorteirinha
São João do Oriente	;	https://www.saojoaodooriente.mg.gov.br/transparencia
Florestal	;	https://florestal.mg.gov.br/portal-da-transparencia/
Felisburgo	;	http://lai.memory.com.br/entidades/login/9A2YUP
São João Batista do Glória	;	http://gloria.mg.gov.br/portaltransparencia/
São José da Barra	;	https://e-gov.betha.com.br/transparencia/01037-108/recursos.faces?mun=O4-Gswt5J9P0bh19PcLEuCKgfvjuZx8K
Alpercata	;	https://alpercata.portaldatransparencia.info/
Indaiabira	;	http://www.cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=indaiabira
Inconfidentes	;	https://www.inconfidentes.mg.gov.br/index.php/governo/transparencia
Sericita	;	https://www
Santo Antônio do Retiro	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=SantoAntoniodoRetiro
Desterro de Entre Rios	;	http://lai.memory.com.br/entidades/login/99LZST
Engenheiro Navarro	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=EngNavrro
Santa Rita de Minas	;	http://santaritademinas-mg.portaltp.com.br/
Reduto	;	https://reduto.mg.gov.br/transparencia/
Delfinópolis	;	http://pmdelfinopolis.horusdm.com.br/transparencia
Machacalis	;	https://www.machacalis.mg.gov.br/transparencia
Santana da Vargem	;	https://portaltransp.com.br/?data=pstv
Pedra Bonita	;	http://www.transparenciafacil.com.br/0190702
São Thomé das Letras	;	https://portal.sgpcloud.net:9016/transparencia/
Guidoval	;	http://transparencia-hd.com.br/?cod_empre=69
São Roque de Minas	;	https://saoroquedeminas.mg.gov.br/transparencia/
Varjão de Minas	;	http://www.adpmnet.com.br/index.php?option=com_contpubl&submenu=1&cnpj=1609780000134&idreg=&tpformtab=jos_coputvcb1&tpformpdf=51&tpform=2&idorg=141&dsorg=Prefeitura%20Municipal%20de%20Varj%C3%A3o%20de%20Minas&dsufe=Estado%20de%20Minas%20Gerais&brasao=P317075.GIF&titulo=Remunera%C3%A7%C3%A3o%20Mensal%20dos%20Servidores%20P%C3%BAblicos&idtpc=0&nome_mat=1&nao_proventos=0&nao_descontos=0
Central de Minas	;	https://centraldeminas-mg.portaltp.com.br/
São Tomás de Aquino	;	https://www.staquino.mg.gov.br/transparencia
Salto da Divisa	;	https://www.saltodadivisa.mg.gov.br/transparencia
Naque	;	https://www.naque.mg.gov.br/transparencia
Abadia dos Dourados	;	http://735c07fc277d.sn.mynetname.net:8093/
Iraí de Minas	;	http://177.85.2.36:8444/transparencia/
Cabeceira Grande	;	https://www.cabeceiragrande.mg.gov.br/
Conquista	;	http://portal.conquista.mg.gov.br:8080/portalcidadao/#efb33c382dcf9e4ae2294337ce2a566034ee25478c90493e56f55878a4d19d547154abb93a539ca141901243121b0442f68667740d76583a9b6fc842805a701255f50abffb83548323feb3d4a215dcba05fc4b5b868699999c1d78af95bbbed2ae7ab27d940f9f7a8b2debb75557ba1cd7f6303c3be5a0edaecf72a00208c722773c5ec1c75725b2
São Miguel do Anta	;	http://www.transparenciafacil.com.br/despesas/0208701
Sapucaí-Mirim	;	http://www.transparenciafacil.com.br/0210502
Comercinho	;	https://transparencia.comercinho.mg.gov.br/
Capetinga	;	https://transparencia.capetinga.mg.gov.br/transparencia
Alfredo Vasconcelos	;	https://pt.alfredovasconcelos.mg.gov.br/
Imbé de Minas	;	http://www.transparenciafacil.com.br/0168402
Indianópolis	;	http://186.232.11.254:8444/transparencia/
Araporã	;	http://transparencia.arapora.mg.gov.br/
Bonfim	;	http://www.mgcidades.com.br/index.php?option=com_contpubl&idcid=310810&mgcidades=1#dv_contpubl
Galiléia	;	http://galileia-mg.portaltp.com.br/
Laranjal	;	https://pm-laranjal.publicacao.siplanweb.com.br/
Periquito	;	https://www.periquito.mg.gov.br/transparencia
Cipotânea	;	https://pm-cipotanea.publicacao.siplanweb.com.br/
Divisa Alegre	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=DivisaAlegre
São Sebastião do Oeste	;	https://e-gov.betha.com.br/transparencia/01037-108/recursos.faces?mun=D-wPfVvPrnSEkHi9iM4JZ8UQBcQPyXd0
Careaçu	;	http://pt.careacu.mg.gov.br/
Tumiritinga	;	https://www.tumiritinga.mg.gov.br/transparencia
Confins	;	http://transparencia.confins.mg.gov.br/
Crisólita	;	https://www.transparencia.crisolita.mg.gov.br/
Luislândia	;	https://www.luislandia.mg.gov.br/portal/transparencia/
Palma	;	https://transparencia.palma.mg.gov.br/
Guarda-Mor	;	http://lai.memory.com.br/pagina-inicial
Dona Eusébia	;	https://prefeitura24horas.online/_transparencia/home/
Heliodora	;	http://www.transparenciafacil.com.br/0166802
São Sebastião do Anta	;	https://transparencia.saosebastiaodoanta.mg.gov.br/servidores-por-nomes
Ijaci	;	https://e-gov.betha.com.br/transparencia/01037-108/recursos.faces?mun=co_ylNyIyVpN9MCJXI_yofrG9D6LcvEB
Mamonas	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=mamonas
São Francisco de Paula	;	https://www.saofranciscodepaula.rs.gov.br/portal/transparencia
Lassance	;	http://transparencia.lassance.mg.gov.br/
Tiros	;	http://179.189.92.246:8444/transparencia/
Vargem Alegre	;	https://vargemalegre-mg.portaltp.com.br/
Bom Jardim de Minas	;	https://pm-bjardim.publicacao.siplanweb.com.br/
São José do Jacuri	;	https://www.transparencia.saojosedojacuri.mg.gov.br/
Mendes Pimentel	;	https://portaltransp.com.br/?data=pmdp
Piracema	;	https://www.piracema.mg.gov.br/transparencia
Padre Carvalho	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=PMPadreCarvalho
Santa Helena de Minas	;	https://transparencia.santahelenademinas.mg.gov.br/
Córrego Fundo	;	http://lai.memory.com.br/entidades/login/99HB3D
Botumirim	;	http://botumirim.mg.gov.br/transparencia/
Catuji	;	https://www.catuji.mg.gov.br/transparencia.php
Sardoá	;	https://www.sardoa.mg.gov.br/transparencia
Inhaúma	;	https://transparencia.inhauma.mg.gov.br/
Luisburgo	;	https://luisburgo.mg.gov.br/transparencia/index.php
Toledo	;	https://pm-toledo.publicacao.siplanweb.com.br/
São Francisco de Sales	;	http://www.saofranciscodesales.mg.gov.br/transparencia
Silvianópolis	;	http://www.adpmnet.com.br/index.php?option=com_contpubl&idorg=18&tpform=1
Pirajuba	;	https://www.pirajuba.mg.gov.br/transparencia
Gonzaga	;	https://gonzaga-mg.portaltp.com.br/consultas/pessoal/servidores.aspx
Soledade de Minas	;	http://transparencia.soledadedeminas.mg.gov.br/
Olhos-d'Água	;	http://www.olhosdagua.mg.gov.br/portal-transparencia
Pai Pedro	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=PaiPedro
Bom Jesus do Amparo	;	http://www.adpmnet.com.br/index.php?option=com_contpubl&submenu=1&cnpj=18317693000106&idreg=&tpformtab=jos_coputvcb1&tpformpdf=51&tpform=2&idorg=100&dsorg=Prefeitura%20Municipal%20de%20Bom%20Jesus%20do%20Amparo&dsufe=Estado%20de%20Minas%20Gerais&brasao=P310770.GIF&titulo=Remunera%C3%A7%C3%A3o%20Mensal%20dos%20Servidores%20P%C3%BAblicos&idtpc=0&nome_mat=1&nao_proventos=0&nao_descontos=0
Itueta	;	https://www.itueta.mg.gov.br/transparencia/
Munhoz	;	http://www.transparenciafacil.com.br/0184302
Itumirim	;	http://pt.itumirim.mg.gov.br/
Divisa Nova	;	https://divisanova.mg.gov.br/portal-da-transparencia/#1595255407052-b6cf5021-5ed1
Aiuruoca	;	https://pm-aiuruoca.publicacao.siplanweb.com.br/
Rubelita	;	http://lai.memory.com.br/entidades/login/9D0S4P
Patis	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=Patis
Cristália	;	http://www.cristalia.mg.gov.br/transparencia/
Pouso Alto	;	http://transparencia.pousoalto.mg.gov.br/
Ouro Verde de Minas	;	https://ouroverdedeminas.mg.gov.br/transparencia
Frei Gaspar	;	https://freigaspar.mg.gov.br/transparencia
São João do Manteninha	;	https://saojoaodomanteninha-mg.portaltp.com.br/
Alto Caparaó	;	https://transparencia.altocaparao.mg.gov.br/
Rio Manso	;	http://www.mgcidades.com.br/index.php?option=com_contpubl&idcid=315530&mgcidades=1#dv_contpubl
Senhora de Oliveira	;	https://pm-soliveira.publicacao.siplanweb.com.br/
Bandeira do Sul	;	https://e-gov.betha.com.br/transparencia/01037-108/recursos.faces?mun=GGQItMTWJxGgGxfmSqX_OOFwzYBPYsDV
Nova União	;	http://www.adpmnet.com.br/index.php?option=com_contpubl&idorg=26&tpform=1
Juvenília	;	http://pmjuvenilia.horusdm.com.br/transparencia/
Veredinha	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=Veredinha
Chalé	;	http://lai.memory.com.br/entidades/login/9958V5
Patrocínio do Muriaé	;	http://www.transparenciafacil.com.br/0190102
São Domingos das Dores	;	https://www.saodomingosdasdores.mg.gov.br/transparencia
Gurinhatã	;	http://gurinhata.sytes.net:65480/portalcidadao/
Mesquita	;	https://www.mesquita.mg.gov.br/transparencia
Cana Verde	;	https://transparencia-hd.com.br/
Sobrália	;	https://www.transparencia.sobralia.mg.gov.br/
Conceição do Pará	;	https://www.conceicaodopara.mg.gov.br/homepage/portal-da-transparencia/
Palmópolis	;	https://palmopolis-mg.portaltp.com.br/
São Sebastião da Bela Vista	;	http://www.transparenciafacil.com.br/0209301
Caiana	;	https://caiana-mg.portaltp.com.br/
Bonfinópolis de Minas	;	http://lai.memory.com.br/entidades/login/98DFNP
Santa Rita do Itueto	;	https://santaritadoitueto-mg.portaltp.com.br/
Rio Preto	;	https://pm-riopreto.publicacao.siplanweb.com.br/
Rio Espera	;	https://publicacao.rioespera.mg.gov.br/
Piranguçu	;	http://www.adpmnet.com.br/index.php?option=com_contpubl&idorg=2&tpform=1
Capitão Andrade	;	https://www.transparencia.capitaoandrade.mg.gov.br/
Luminárias	;	http://pt.luminarias.mg.gov.br/
Caparaó	;	https://caparao-mg.portaltp.com.br/
São José do Goiabal	;	http://www.transparenciafacil.com.br/0208302
Itaverava	;	https://pt.itaverava.mg.gov.br/
Datas	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=Datas
Jampruca	;	https://jampruca-mg.portaltp.com.br/
Ibiracatu	;	https://ibiracatu.mg.gov.br/?page_id=197
Barão de Monte Alto	;	https://prefeitura24horas.online/_transparencia/home/
Franciscópolis	;	https://pmfranciscopolis-transparencia.gpecloud.com.br/
Itacambira	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=Itacambira
Virgolândia	;	https://virgolandia-mg.portaltp.com.br/
Catas Altas	;	https://portaltransparencia.catasaltas.mg.gov.br/
Entre Folhas	;	https://www.entrefolhas.mg.gov.br/leideacesso/menu-transparencia
Fruta de Leite	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=FrutadeLeite
Presidente Bernardes	;	http://transparencia.presidentebernardes.mg.gov.br/Home
Senador Amaral	;	https://senadoramaral.mg.gov.br/portal-da-transparencia/
Novorizonte	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=Novorizonte
São Bento Abade	;	https://www.municipalnet.com.br/index/?uid=sao-bento-abade
Volta Grande	;	https://pm-vgrande.publicacao.siplanweb.com.br/
São Pedro do Suaçuí	;	http://www.adpmnet.com.br/index.php?option=com_contpubl&idorg=198&tpform=1
Dom Silvério	;	http://www.adpmnet.com.br/index.php?option=com_contpubl&submenu=1&cnpj=18297226000161&idreg=&tpformtab=jos_coputvcb1&tpformpdf=51&tpform=2&idorg=453&dsorg=Prefeitura%20Municipal%20de%20Dom%20Silv%C3%A9rio&dsufe=Estado%20de%20Minas%20Gerais&brasao=P312270.GIF&titulo=Remunera%C3%A7%C3%A3o%20Mensal%20dos%20Servidores%20P%C3%BAblicos&idtpc=0&nome_mat=1&nao_proventos=0&nao_descontos=0
Santa Maria do Salto	;	http://lai.memory.com.br/entidades/login/9D5ZCP
Aricanduva	;	http://www.cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=Aricanduva
Francisco Dumont	;	https://www.franciscodumont.mg.gov.br/transparencia/portal-da-transparencia
Jequitibá	;	https://transparencia.altojequitiba.mg.gov.br/
Dores de Guanhães	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=CamDoresDeGanhaes
Cristiano Otoni	;	https://www.cristianootoni.mg.gov.br/acesso-a-informacao
Rio do Prado	;	https://riodoprado-mg.portaltp.com.br/
Barra Longa	;	https://pm-blonga.publicacao.siplanweb.com.br/
Gameleiras	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=Gameleiras
Madre de Deus de Minas	;	https://pm-madredeus.publicacao.siplanweb.com.br/
Bocaina de Minas	;	https://pm-bocaina.publicacao.siplanweb.com.br/
Dom Cavati	;	https://transparencia.domcavati.mg.gov.br/principal
Liberdade	;	https://cmliberdade-mg.portaltp.com.br/
Congonhas do Norte	;	http://congonhasdonorte-mg.portaltp.com.br/
Turvolândia	;	http://www.transparenciafacil.com.br/0215701
Crucilândia	;	http://www.contasabertas.inf.br/abre/6512bd43d9caa6e02c990b0a82652dca
Ibertioga	;	https://pm-ibertioga.publicacao.siplanweb.com.br/
Descoberto	;	http://pt.descoberto.mg.gov.br/Principal
Vargem Grande do Rio Pardo	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=VgmGrnd
São José da Varginha	;	http://lai.memory.com.br/entidades/login/9DL0LP
José Raydan	;	https://joseraydan-mg.portaltp.com.br/
Catuti	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=Catuti
Cuparaque	;	https://www.cuparaque.mg.gov.br/transparencia/
Piedade dos Gerais	;	https://piedadedepontenova.mg.gov.br/acesso-a-informacao
Divino das Laranjeiras	;	http://divinodaslaranjeiras-mg.portaltp.com.br/
Guaraciama	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=PMGuaraciama
Pingo d'Água	;	http://www.pingodagua.mg.gov.br/transparencia
Moeda	;	https://moeda-mg.portaltp.com.br/
Leme do Prado	;	https://www.lemedoprado.mg.gov.br/transparencia
São João da Lagoa	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=SJDLgoa
Jeceaba	;	http://pt.jeceaba.mg.gov.br/
Monte Formoso	;	https://www.monteformoso.mg.gov.br/transparencia
Miravânia	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=miravania
Santa Rita de Jacutinga	;	http://www.srjacutinga.mg.gov.br/?page_id=110
Augusto de Lima	;	http://www.augustodelima.mg.gov.br/index.php/portal-da-transparencia
Josenópolis	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=Josenopolis
São Francisco do Glória	;	https://saofranciscodogloria-mg.portaltp.com.br/
Claraval	;	http://www.transparenciafacil.com.br/0151802
Vermelho Novo	;	https://transparencia.vermelhonovo.mg.gov.br/transparencia
Paulistas	;	https://transparencia.paulistas.mg.gov.br/
Santana do Jacaré	;	http://pt.santanadojacare.mg.gov.br/Principal
Ressaquinha	;	http://pt.ressaquinha.mg.gov.br/
Braúnas	;	https://www.braunas.mg.gov.br/transparencia/portal-da-transparencia.html
Bandeira	;	https://www.bandeira.mg.gov.br/transparencia
Jesuânia	;	http://transparencia.jesuania.mg.gov.br/
Serranópolis de Minas	;	http://lai.memory.com.br/entidades/login/9E0P1H
Tapira	;	http://167.249.84.86:8444/transparencia/
Santa Cruz do Escalvado	;	http://www.santacruzdoescalvado.mg.gov.br/index.php/santa-cruz-transparente
Felício dos Santos	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=FelicioSantos
Berizal	;	https://berizal-mg.portaltp.com.br/
Natércia	;	http://www.transparenciafacil.com.br/0185101
Amparo do Serra	;	http://www.mgcidades.com.br/index.php?option=com_contpubl&idcid=310250&mgcidades=1
Joaquim Felício	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=JquimFelicio
Espírito Santo do Dourado	;	https://www.municipalnet.com.br/index/?uid=espirito-santo-do-dourado
São Pedro da União	;	https://www.saopedrodauniao.mg.gov.br/transparencia/portal-da-transparencia/portal-da-transparencia-ate-2017
Oratórios	;	https://pm-oratorios.publicacao.siplanweb.com.br/
Capela Nova	;	http://lai.memory.com.br/entidades/login/98PMY1
Bertópolis	;	https://www.bertopolis.mg.gov.br/transparencia
Ritápolis	;	http://pt.ritapolis.mg.gov.br/
Rosário da Limeira	;	http://www.rosariodalimeira.mg.gov.br/site/transparencia/TransparenciaPreviliP2017.php
Fronteira dos Vales	;	https://www.fronteiradosvales.mg.gov.br/transparencia
Conceição de Ipanema	;	https://www.conceicaodeipanema.mg.gov.br/transparencia
Joanésia	;	https://www.joanesia.mg.gov.br/transparencia
Canaã	;	https://pm-canaa.publicacao.siplanweb.com.br/
Cantagalo	;	https://www.cantagalo.mg.gov.br/transparencia
José Gonçalves de Minas	;	http://josegoncalvesdeminas-mg.portaltp.com.br/
Piedade do Rio Grande	;	http://ptn.piedadedoriogrande.mg.gov.br/Folha
Aguanil	;	https://transparencia-hd.com.br/
Paineiras	;	http://adpmnet.com.br/index.php?option=com_contpubl&idorg=454&tpform=1
Carvalhos	;	https://www.carvalhos.mg.gov.br/portal-da-transparencia/
Materlândia	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=Materlandia
Santa Bárbara do Tugúrio	;	http://pt.santabarbaradotugurio.mg.gov.br/
São João do Pacuí	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=SaoJoaoPacui
Fortaleza de Minas	;	http://fortalezademinas-mg.portaltp.com.br/
Couto de Magalhães de Minas	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=CoutoMagalhaes
Santa Efigênia de Minas	;	https://www.santaefigenia.mg.gov.br/transparencia
Pequi	;	https://www.pequi.mg.gov.br/pagina/view/2
Itamarati de Minas	;	https://prefeitura24horas.online/_transparencia/home/
Gonçalves	;	http://portaltransparencia.goncalves.mg.gov.br/
Japaraíba	;	https://www.japaraiba.mg.gov.br/transparencia
Funilândia	;	http://lai.memory.com.br/entidades/login/9A7F6P
Brás Pires	;	https://pm-braspires.publicacao.siplanweb.com.br/
Juramento	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=Juramento
União de Minas	;	http://www.uniaodeminas.mg.gov.br/transparencia
Santana do Riacho	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=PmSantanaDoRiacho
Serra Azul de Minas	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=SerraAzulDeMinas
São José da Safira	;	http://saojosedasafira-mg.portaltp.com.br/
Ponto Chique	;	https://www.pontochique.mg.gov.br/site/institucional/13/portal-da-transparencia.html
Dores do Turvo	;	http://www.contasabertas.inf.br/abre/c20ad4d76fe97759aa27a0c99bff6710
Pescador	;	https://www.pescador.mg.gov.br/transparencia
Ipiaçu	;	http://200.146.202.92:8080/portalcidadao/
Bom Jesus da Penha	;	https://www.bomjesusdapenha.mg.gov.br/transparencia_publica
São José do Alegre	;	https://www.saojosedoalegre.mg.gov.br/transparencia
Dom Joaquim	;	http://lai.memory.com.br/entidades/login/99PDMD
Senador Modestino Gonçalves	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=SenModestino
Santa Cruz de Salinas	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=SantaCruzDeSalinas
Piedade de Ponte Nova	;	https://piedadedepontenova.mg.gov.br/acesso-a-informacao
Marilac	;	https://www.marilac.mg.gov.br/transparencia
Lagoa dos Patos	;	http://lagoadospatos.mg.gov.br/transparencia/
Tocos do Moji	;	http://www.transparenciafacil.com.br/0214802
Taquaraçu de Minas	;	http://taquaracudeminas.mg.gov.br/servicos/
Carrancas	;	http://ptn.carrancas.mg.gov.br/
Marliéria	;	http://www.transparenciafacil.com.br/0180102
Ribeirão Vermelho	;	https://ribeiraovermelho.mg.gov.br/transparencia/
São Geraldo do Baixio	;	https://saogeraldodobaixio-mg.portaltp.com.br/
Veríssimo	;	http://pmvportaldatransparencia.com.br:8444/transparencia/
Acaiaca	;	https://transparencia.acaiaca.mg.gov.br/
Cajuri	;	https://www.cajuri.mg.gov.br/transparencia
Bugre	;	https://www.bugre.mg.gov.br/transparencia
Santana do Deserto	;	https://santanadodeserto.mg.gov.br/transparencia/
Pedra do Indaiá	;	http://lai.memory.com.br/pagina-inicial
Goianá	;	https://www.goiana.mg.gov.br/transparencia.html
São Geraldo da Piedade	;	https://saogeraldodapiedade-mg.portaltp.com.br/
Conceição da Barra de Minas	;	http://ptn.cbm.mg.gov.br/
Ewbank da Câmara	;	https://pm-ewbanck.publicacao.siplanweb.com.br/
Santo Antônio do Grama	;	http://www.transparenciafacil.com.br/0203702
Alvarenga	;	https://www.alvarenga.mg.gov.br/transparencia
Minduri	;	https://pm-minduri.publicacao.siplanweb.com.br/
Santana de Cataguases	;	https://www.santanadecataguases.mg.gov.br/transparencia
São José do Divino	;	https://www.saojosedodivino.mg.gov.br/transparencia
Santa Fé de Minas	;	https://santafedeminas.mg.gov.br/transparencia/
Santo Antônio do Itambé	;	https://transparencia.santoantoniodoitambe.mg.gov.br/
Campo Azul	;	https://www.campoazul.mg.gov.br/portal-transparencia
Diogo de Vasconcelos	;	https://pm-dvasconcelos.publicacao.siplanweb.com.br/
Medeiros	;	http://lai.memory.com.br/entidades/display
Guarará	;	https://pm-guarara.publicacao.siplanweb.com.br/
Itutinga	;	http://ptn.itutinga.mg.gov.br/
Santana dos Montes	;	http://pt.santanadosmontes.mg.gov.br/
Tabuleiro	;	https://pm-tabuleiro.publicacao.siplanweb.com.br/
Matutina	;	https://transparencia-hd.com.br/
São Brás do Suaçuí	;	http://pt.saobrasdosuacui.mg.gov.br/
Campanário	;	https://transparencia.campanario.mg.gov.br/servidores/
Córrego do Bom Jesus	;	http://www.corregodobomjesus.mg.gov.br/transp.php
Dom Bosco	;	http://lai.memory.com.br/entidades/login/99P0MP
Catas Altas da Noruega	;	https://pt.catasaltasdanoruega.mg.gov.br/
Presidente Juscelino	;	https://presidentejuscelino-mg.portaltp.com.br/
Pedrinópolis	;	http://pedrinopolis.ddns.com.br:8444/transparencia/
Cruzeiro da Fortaleza	;	http://138.0.67.146:8444/transparencia/
Vieiras	;	http://lai.memory.com.br/entidades/login/9EEB79
Alvorada de Minas	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=alvoradademinas
Cachoeira da Prata	;	http://lai.memory.com.br/entidades/login/98HNS1
Pratinha	;	http://201.71.44.3:8445/transparencia/
Santo Antônio do Aventureiro	;	http://www.pmsaa.mg.gov.br/transparencia/
Nova Módica	;	https://www.novamodica.mg.gov.br/transparencia/
Carvalhópolis	;	http://www.transparenciafacil.com.br/0149801
Quartel Geral	;	http://www.mgcidades.com.br/index.php?option=com_contpubl&idcid=315370&mgcidades=1
Cordislândia	;	https://www.cordislandia.mg.gov.br/transparencia
Romaria	;	http://177.185.100.233:8444/transparencia/
Senhora do Porto	;	https://senhoradoporto-mg.portaltp.com.br/
Estrela do Indaiá	;	http://201.16.156.251:8095/
Ibitiúra de Minas	;	https://www.ibitiurademinas.mg.gov.br/transparencia.php
Frei Lagonegro	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=PMFreiLagoNegro
Coronel Xavier Chaves	;	http://pt.coronelxavierchaves.mg.gov.br/
Fernandes Tourinho	;	https://www.fernandestourinho.mg.gov.br/transparencia
Belmiro Braga	;	https://pm-bbraga.publicacao.siplanweb.com.br/
Santa Rita de Ibitipoca	;	https://pm-sribitipoca.publicacao.siplanweb.com.br/
Divinésia	;	http://transparencia.divinesia.mg.gov.br/
Lamim	;	https://pm-lamim.publicacao.siplanweb.com.br/
Bias Fortes	;	https://pm-biasfortes.publicacao.siplanweb.com.br/
São Félix de Minas	;	http://saofelixdeminas-mg.portaltp.com.br/
Goiabeira	;	https://www.transparencia.goiabeira.mg.gov.br/
Santa Rosa da Serra	;	http://lai.memory.com.br/entidades/login/9DAKR1
Pequeri	;	http://publicacao.pm-pequeri.siplanweb.com.br/
Natalândia	;	https://www.natalandia.mg.gov.br/publicacoes/
Uruana de Minas	;	http://lai.memory.com.br/entidades/login/9EBH2T
Faria Lemos	;	https://farialemos-mg.portaltp.com.br/
Leandro Ferreira	;	https://www.leandroferreira.mg.gov.br/transparencia-1/portal-da-transparencia
Nacip Raydan	;	https://nacipraydan-mg.portaltp.com.br/
Córrego Danta	;	http://lai.memory.com.br/entidades/login/99GSKT
Mathias Lobato	;	https://transparencia.mathiaslobato.mg.gov.br/
Nova Belém	;	https://transparencia.novabelem.mg.gov.br/
Caranaíba	;	http://pt.caranaiba.mg.gov.br/Folha
Morro do Pilar	;	https://morrodopilar-mg.portaltp.com.br/
São Gonçalo do Rio Preto	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=SaoGoncaloDoRioPreto
Chácara	;	https://pm-chacara.publicacao.siplanweb.com.br/
Glaucilândia	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=Glaucilandia
Santa Bárbara do Monte Verde	;	http://www.santabarbaradomonteverde.mg.gov.br/portal-da-transparencia-2/
Onça de Pitangui	;	http://lai.memory.com.br/entidades/login/9C0779
Jaguaraçu	;	https://www.jaguaracu.mg.gov.br/transparencia
Comendador Gomes	;	http://pmcgomes.horusdm.com.br/transparencia
Taparuba	;	http://lai.memory.com.br/entidades/login/9E43VD
Santo Hipólito	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=SantoHipolito
Coronel Pacheco	;	https://pm-cpacheco.publicacao.siplanweb.com.br/
Cascalho Rico	;	http://138.0.191.102:8444/transparencia/
Pedra do Anta	;	http://www.transparenciafacil.com.br/0190801
Albertina	;	https://albertina.mg.gov.br/site/transparencia/contas-publicas-2/
São Sebastião da Vargem Alegre	;	https://saosebastiaodavargemalegre.mg.gov.br/transparencia/?id=diarias
Presidente Kubitschek	;	http://cidadesmg.com.br/portaltransparencia/faces/user/portal.xhtml?Param=PresKubitschek
Dom Viçoso	;	https://pm-dvicoso.publicacao.siplanweb.com.br/
Ibituruna	;	http://pt.ibituruna.mg.gov.br/Folha
Maripá de Minas	;	https://pm-maripa.publicacao.siplanweb.com.br/
Fortuna de Minas	;	http://lai.memory.com.br/entidades/login/9A512P
Camacho	;	http://pt.camacho.mg.gov.br/
Desterro do Melo	;	http://lai.memory.com.br/entidades/login/99M2Y9
Arapuá	;	http://transparencia.arapua.mg.gov.br/
Conceição das Pedras	;	https://www.conceicaodaspedras.mg.gov.br/transparencia
Arantina	;	https://pm-arantina.publicacao.siplanweb.com.br/
São José do Mantimento	;	https://www.pmsjmantimento.mg.gov.br/transparencia
Olímpio Noronha	;	http://transparencia.olimpionoronha.mg.gov.br/
Córrego Novo	;	http://www.corregonovo.mg.gov.br/transparencia
Ingaí	;	http://pt.ingai.mg.gov.br/
Marmelópolis	;	http://www.adpmnet.com.br/index.php?option=com_contpubl&idorg=41&tpform=1
São João da Mata	;	http://www.adpmnet.com.br/index.php?option=com_contpubl&submenu=1&cnpj=17935206000106&idreg=&tpformtab=jos_coputvcb1&tpformpdf=51&tpform=2&idorg=189&dsorg=Prefeitura%20Municipal%20de%20S%C3%A3o%20Jo%C3%A3o%20Da%20Mata&dsufe=Estado%20de%20Minas%20Gerais&brasao=P316230.GIF&titulo=Remunera%C3%A7%C3%A3o%20Mensal%20dos%20Servidores%20P%C3%BAblicos&idtpc=0&nome_mat=1&nao_proventos=0&nao_descontos=0
Piau	;	https://pm-piau.publicacao.siplanweb.com.br/
Argirita	;	https://transparencia.argirita.mg.gov.br/
Cachoeira Dourada	;	http://190.89.156.57:8089/portalcidadao/
Chiador	;	https://pm-chiador.publicacao.siplanweb.com.br/
Alagoa	;	http://transparencia.alagoa.mg.gov.br/
Sem-Peixe	;	https://sempeixe.mg.gov.br/acesso-a-informacao
Carmésia	;	https://transparencia.carmesia.mg.gov.br/
Simão Pereira	;	https://pm-spereira.publicacao.siplanweb.com.br/licitacoes/painel
Umburatiba	;	https://www.umburatiba.mg.gov.br/transparencia
Rio Doce	;	https://www.riodoce.mg.gov.br/index.php/transparencia
Wenceslau Braz	;	http://www.adpmnet.com.br/index.php?option=com_contpubl&submenu=1&cnpj=18026013000103&idreg=&tpformtab=jos_coputvcb1&tpformpdf=51&tpform=2&idorg=144&dsorg=Prefeitura%20Municipal%20de%20Wenceslau%20Braz&dsufe=Estado%20de%20Minas%20Gerais&brasao=P317220.GIF&titulo=Remunera%C3%A7%C3%A3o%20Mensal%20dos%20Servidores%20P%C3%BAblicos&idtpc=0&nome_mat=1&nao_proventos=0&nao_descontos=0
Biquinhas	;	http://www.adpmnet.com.br/index.php?option=com_contpubl&submenu=1&cnpj=18296640000156&idreg=&tpformtab=jos_coputvcb1&tpformpdf=51&tpform=2&idorg=99&dsorg=Prefeitura%20Municipal%20de%20Biquinhas&dsufe=Estado%20de%20Minas%20Gerais&brasao=PADRAO.GIF&titulo=Remunera%C3%A7%C3%A3o%20Mensal%20dos%20Servidores%20P%C3%BAblicos&idtpc=0&nome_mat=1&nao_proventos=0&nao_descontos=0
Pedra Dourada	;	http://www.transparenciafacil.com.br/servidores-por-nomes/0191002
Morro da Garça	;	http://lai.memory.com.br/entidades/login/9BPH25
Santana do Garambéu	;	https://pm-sgarambeu.publicacao.siplanweb.com.br/
Fama	;	http://www.fama.mg.gov.br/servicos
Araçaí	;	http://lai.memory.com.br/entidades/login/97U7HT
Estrela Dalva	;	https://estreladalva.mg.gov.br/portal-da-transparencia/
Rochedo de Minas	;	https://pm-rochedo.publicacao.siplanweb.com.br/
Silveirânia	;	http://pt.silveirania.mg.gov.br/
Casa Grande	;	http://pt.casagrande.mg.gov.br/
São Sebastião do Rio Verde	;	http://transparencia.saosebastiaodorioverde.mg.gov.br/#
Monjolos	;	http://lai.memory.com.br/entidades/login/9BM4UP
Vargem Bonita	;	http://lai.memory.com.br/entidades/login/9EBT39
Oliveira Fortes	;	http://www.contasabertas.inf.br/abre/c51ce410c124a10e0db5e4b97fc2af39
Itambé do Mato Dentro	;	http://lai.memory.com.br/pagina-inicial
Aracitaba	;	https://pm-aracitaba.publicacao.siplanweb.com.br/
Passa Vinte	;	https://pm-pvinte.publicacao.siplanweb.com.br/
Senador Cortes	;	https://pm-scortes.publicacao.siplanweb.com.br/
Água Comprida	;	http://138.122.49.239:8444/transparencia/
Serranos	;	http://transparencia.serranos.mg.gov.br/
Queluzito	;	http://pt.queluzito.mg.gov.br/
Douradoquara	;	http://transparencia-hd.com.br/?cod_empre=62
Tapiraí	;	https://e-gov.betha.com.br/transparencia/01037-108/recursos.faces?mun=lLbWM9rNqIfA6Op1TBRrBCOEKlUAd9oD
Seritinga	;	https://pm-seritinga.publicacao.siplanweb.com.br/
Pedro Teixeira	;	https://pm-pteixeira.publicacao.siplanweb.com.br/
Consolação	;	http://www.adpmnet.com.br/index.php?option=com_contpubl&Itemid=157&idorg=112&tpform=1
Santo Antônio do Rio Abaixo	;	http://lai.memory.com.br/entidades/login/9DD2V1
Olaria	;	https://pm-olaria.publicacao.siplanweb.com.br/
Passabém	;	http://www.contasabertas.inf.br/abre/8f14e45fceea167a5a36dedd4bea2543
Antônio Prado de Minas	;	http://lai.memory.com.br/pagina-inicial
Paiva	;	https://www.paiva.mg.gov.br/transparencia
Doresópolis	;	http://lai.memory.com.br/entidades/login/99RRQD
São Sebastião do Rio Preto	;	http://saosebastiaodoriopreto.mg.gov.br/transparenciamunicipal/
Senador José Bento	;	http://www.transparenciafacil.com.br/0211202
Grupiara	;	http://179.189.0.196:8444/transparencia/
Cedro do Abaeté	;	http://www.adpmnet.com.br/index.php?option=com_contpubl&idorg=109&tpform=1
Serra da Saudade	;	http://serradasaudade.com/recursos_humanos.html"""



municipios = municipios.split("\n")

dic = {"adpmnet": "ADPM", "facil": "Portal Facil", "memory": "Memory", "pm-": "Siplanweb", "portatp": "Portal TP", "portalcidadao": "GRP"}

data = []
for mun in municipios:
  aux = mun.split(";")
  added = False
  for key, value in dic.items():
    if key in aux[1]:
      data.append([aux[0].replace("\t", ""), aux[1].replace("\t", ""), value])
      added = True

  if not added:
    data.append([aux[0].replace("\t", ""), aux[1].replace("\t", ""), ""])

import pandas as pd

df = pd.DataFrame(data, columns = ["Municipio", "Url", "Template"])

df

def buscaPorTemplate(template):

  return df[df["Template"] == template]

buscaPorTemplate("ADPM")

def buscaPorCidade(cidade):

  return df[df["Municipio"] == cidade]

buscaPorCidade("Belo Horizonte")

